<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bulk Asset Accountability Forms - {{ $formData['form_id'] }}</title>
    <style>
        @page {
            margin: 0.5in;
            size: A4;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
            margin: 0;
            padding: 0;
        }
        
        .header {
            border-bottom: 3px solid #2c3e50;
            padding-bottom: 15px;
            margin-bottom: 20px;
        }
        
        .header h1 {
            color: #2c3e50;
            font-size: 24px;
            margin: 0;
            font-weight: bold;
        }
        
        .header .subtitle {
            color: #7f8c8d;
            font-size: 14px;
            margin-top: 5px;
        }
        
        .form-meta {
            background: #f8f9fa;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #3498db;
        }
        
        .asset-section {
            margin-bottom: 30px;
            page-break-inside: avoid;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 15px;
        }
        
        .asset-header {
            background: #34495e;
            color: white;
            padding: 8px 12px;
            margin: -15px -15px 15px -15px;
            font-size: 14px;
            font-weight: bold;
            border-radius: 3px 3px 0 0;
        }
        
        .info-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 15px;
            margin-bottom: 15px;
        }
        
        .info-item {
            border: 1px solid #ddd;
            padding: 8px;
            border-radius: 3px;
        }
        
        .info-label {
            font-weight: bold;
            color: #2c3e50;
            font-size: 10px;
            text-transform: uppercase;
            margin-bottom: 3px;
        }
        
        .info-value {
            color: #333;
            font-size: 11px;
        }
        
        .status-badge {
            display: inline-block;
            padding: 2px 6px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
            text-transform: uppercase;
        }
        
        .status-active {
            background: #d4edda;
            color: #155724;
        }
        
        .status-assigned {
            background: #cce5ff;
            color: #004085;
        }
        
        .status-pending {
            background: #fff3cd;
            color: #856404;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            font-size: 10px;
            color: #666;
            text-align: center;
        }
        
        .print-only {
            display: block;
        }
        
        .no-print {
            display: none;
        }
        
        @media print {
            .no-print {
                display: none !important;
            }
            
            .print-only {
                display: block !important;
            }
            
            body {
                font-size: 11px;
            }
            
            .asset-section {
                page-break-inside: avoid;
            }
        }
        
        .summary-section {
            background: #e9ecef;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
            border-left: 4px solid #17a2b8;
        }
    </style>
</head>
<body>
    <!-- Header -->
    <div class="header">
        <h1>BULK ASSET ACCOUNTABILITY FORMS</h1>
        <div class="subtitle">ICT Asset Management System - Multiple Asset Audit Trail</div>
    </div>

    <!-- Form Metadata -->
    <div class="form-meta">
        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">Form ID</div>
                <div class="info-value">{{ $formData['form_id'] }}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Generated Date</div>
                <div class="info-value">{{ $formData['generated_at']->format('F d, Y \a\t g:i A') }}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Generated By</div>
                <div class="info-value">{{ $formData['generated_by']->first_name }} {{ $formData['generated_by']->last_name }}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Total Assets</div>
                <div class="info-value">{{ $formData['assets']->count() }}</div>
            </div>
        </div>
    </div>

    <!-- Summary Section -->
    <div class="summary-section">
        <h3 style="margin-top: 0; color: #2c3e50;">Summary</h3>
        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">Total Assets</div>
                <div class="info-value">{{ $formData['assets']->count() }}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Active Assets</div>
                <div class="info-value">{{ $formData['assets']->where('status', 'Active')->count() }}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Assigned Assets</div>
                <div class="info-value">{{ $formData['assets']->where('status', 'Assigned')->count() }}</div>
            </div>
            <div class="info-item">
                <div class="info-label">Pending Confirmation</div>
                <div class="info-value">{{ $formData['assets']->where('status', 'Pending Confirmation')->count() }}</div>
            </div>
        </div>
    </div>

    <!-- Individual Asset Forms -->
    @foreach($formData['assets'] as $index => $asset)
        <div class="asset-section">
            <div class="asset-header">
                Asset {{ $index + 1 }} of {{ $formData['assets']->count() }}: {{ $asset->asset_tag }}
            </div>
            
            <div class="info-grid">
                <div class="info-item">
                    <div class="info-label">Asset Name</div>
                    <div class="info-value">{{ $asset->name }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Asset Tag</div>
                    <div class="info-value">{{ $asset->asset_tag }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Serial Number</div>
                    <div class="info-value">{{ $asset->serial_number }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Model</div>
                    <div class="info-value">{{ $asset->model ?? 'N/A' }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Category</div>
                    <div class="info-value">{{ $asset->category->name ?? 'N/A' }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Vendor</div>
                    <div class="info-value">{{ $asset->vendor->name ?? 'N/A' }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Purchase Date</div>
                    <div class="info-value">{{ $asset->purchase_date ? $asset->purchase_date->format('M d, Y') : 'N/A' }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Cost</div>
                    <div class="info-value">₱{{ number_format($asset->cost, 2) }}</div>
                </div>
                <div class="info-item">
                    <div class="info-label">Current Status</div>
                    <div class="info-value">
                        <span class="status-badge status-{{ strtolower(str_replace(' ', '-', $asset->status)) }}">
                            {{ $asset->status }}
                        </span>
                    </div>
                </div>
                <div class="info-item">
                    <div class="info-label">Location</div>
                    <div class="info-value">{{ $asset->location ?? 'N/A' }}</div>
                </div>
            </div>

            @if($asset->assignedUser)
                <h4 style="color: #2c3e50; margin-top: 20px; margin-bottom: 10px;">Current Assignment</h4>
                <div class="info-grid">
                    <div class="info-item">
                        <div class="info-label">Assigned To</div>
                        <div class="info-value">
                            {{ $asset->assignedUser->first_name }} {{ $asset->assignedUser->last_name }}
                        </div>
                    </div>
                    <div class="info-item">
                        <div class="info-label">Email Address</div>
                        <div class="info-value">{{ $asset->assignedUser->email }}</div>
                    </div>
                    <div class="info-item">
                        <div class="info-label">Employee Number</div>
                        <div class="info-value">{{ $asset->assignedUser->employee_no ?? 'N/A' }}</div>
                    </div>
                    <div class="info-item">
                        <div class="info-label">Position</div>
                        <div class="info-value">{{ $asset->assignedUser->position ?? 'N/A' }}</div>
                    </div>
                    <div class="info-item">
                        <div class="info-label">Department</div>
                        <div class="info-value">{{ $asset->assignedUser->department->name ?? 'N/A' }}</div>
                    </div>
                    <div class="info-item">
                        <div class="info-label">Assignment Date</div>
                        <div class="info-value">
                            {{ $asset->assigned_date ? $asset->assigned_date->format('M d, Y \a\t g:i A') : 'N/A' }}
                        </div>
                    </div>
                </div>
            @else
                <div style="background: #f8d7da; color: #721c24; padding: 10px; border-radius: 3px; margin-top: 15px;">
                    <strong>No Current Assignment:</strong> This asset is not currently assigned to any user.
                </div>
            @endif
        </div>
    @endforeach

    <!-- Footer -->
    <div class="footer">
        <p><strong>ICT Asset Management System - Bulk Accountability Forms</strong></p>
        <p>This bulk form was generated on {{ $formData['generated_at']->format('F d, Y \a\t g:i A T') }}</p>
        <p>Form ID: {{ $formData['form_id'] }} | Generated by: {{ $formData['generated_by']->first_name }} {{ $formData['generated_by']->last_name }}</p>
        <p>Total Assets: {{ $formData['assets']->count() }}</p>
        <p class="no-print">This is a system-generated document. For questions, contact the IT Department.</p>
    </div>

    <!-- Print Button (Hidden in print) -->
    <div class="no-print" style="position: fixed; top: 20px; right: 20px; z-index: 1000;">
        <button onclick="window.print()" class="btn btn-primary">
            <i class="fas fa-print me-1"></i>
            Print Forms
        </button>
        <button onclick="window.close()" class="btn btn-secondary ms-2">
            <i class="fas fa-times me-1"></i>
            Close
        </button>
    </div>
</body>
</html>
